### ISSUE TITLE
[Feature Request]  enable usage of aws keyspace

### ISSUE THREAD

**Issue by FormindAPE** [StrangeBeeCorp/TheHive-feedback#7]
### Request Type

Feature Request

### Feature Description

Make thieve work with aws keyspace

### Possible Solutions

Upgrade the janusgraph library to a newest version (minimum v0.6.2) as there was a bug preventing connection in the previews version (see [janusgraph issues #3050](https://github.com/JanusGraph/janusgraph/issues/3050))

### Complementary information

log of the probleme
```
docker-th5-thehive-1 | org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend
docker-th5-thehive-1 | at io.vavr.API$Match$Case0.apply(API.java:5135)
docker-th5-thehive-1 | at io.vavr.API$Match.of(API.java:5092)
docker-th5-thehive-1 | at org.janusgraph.diskstorage.cql.CQLKeyColumnValueStore.lambda$static$0(CQLKeyColumnValueStore.java:120)
docker-th5-thehive-1 | at io.vavr.control.Try.getOrElseThrow(Try.java:748)
docker-th5-thehive-1 | at org.janusgraph.diskstorage.cql.function.slice.CQLExecutorServiceSliceFunction.getSlice(CQLExecutorServiceSliceFunction.java:49)
docker-th5-thehive-1 | at org.janusgraph.diskstorage.cql.function.slice.AbstractCQLSliceFunction.getSlice(AbstractCQLSliceFunction.java:48)
docker-th5-thehive-1 | at org.janusgraph.diskstorage.cql.CQLKeyColumnValueStore.getSlice(CQLKeyColumnValueStore.java:359)
docker-th5-thehive-1 | at org.janusgraph.diskstorage.keycolumnvalue.KCVSProxy.getSlice(KCVSProxy.java:82)
docker-th5-thehive-1 | at org.janusgraph.diskstorage.configuration.backend.KCVSConfiguration$1.call(KCVSConfiguration.java:99)
docker-th5-thehive-1 | at org.janusgraph.diskstorage.configuration.backend.KCVSConfiguration$1.call(KCVSConfiguration.java:96)
docker-th5-thehive-1 | Caused by: java.util.concurrent.ExecutionException: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: Consistency level QUORUM is not supported for this operation. Supported consistency levels are: ONE, LOCAL_QUORUM, LOCAL_ONE
docker-th5-thehive-1 | at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
docker-th5-thehive-1 | at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
docker-th5-thehive-1 | at io.vavr.control.Try.of(Try.java:75)
docker-th5-thehive-1 | at io.vavr.concurrent.Future.lambda$of$11(Future.java:497)
docker-th5-thehive-1 | at io.vavr.concurrent.FutureImpl.lambda$null$3(FutureImpl.java:157)
docker-th5-thehive-1 | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
docker-th5-thehive-1 | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
docker-th5-thehive-1 | at java.base/java.lang.Thread.run(Thread.java:829)
docker-th5-thehive-1 | Caused by: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: Consistency level QUORUM is not supported for this operation. Supported consistency levels are: ONE, LOCAL_QUORUM, LOCAL_ONE
```

**Comment by vdebergue** [comment]
Hello, TheHive 5.1 will include this updated version
